version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: torb
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
  web:
    build: .
    volumes:
      - .:/myapp
    environment:
      DB_USER: isucon
      DB_PASS: isucon
      DB_DATABASE: torb
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "9292:9292"
    tty: true
    depends_on:
      - db